{{- $databaseBackend := .Values.backend.database -}}
{{- if not $databaseBackend.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datakern.fullname" . }}-database-backend
  labels:
    {{- include "datakern.labels" . | nindent 4 }}
type: Opaque
data:
  dbname: {{ $databaseBackend.name | b64enc | quote }}
  user: {{ $databaseBackend.username | b64enc | quote }}
  password: {{ $databaseBackend.password | b64enc | quote |  }}
  host: {{ $databaseBackend.host | b64enc | quote }}
  port: {{ $databaseBackend.port | b64enc | quote }}
{{- end }}