{{- $databaseBackend := .Values.backend.database -}}
{{- $databaseBuiltin := .Values.airflow.postgresql.auth -}}
{{- if not $databaseBackend.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "datakern.fullname" . }}-database-backend
  labels:
    {{- include "datakern.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.airflow.postgresql.enabled }}
  dbname: {{ $databaseBuiltin.database | b64enc | quote }}
  user: {{ $databaseBuiltin.username | b64enc | quote }}
  password: {{ $databaseBuiltin.password | b64enc | quote }}
  host: {{ printf "%s-database" .Release.Name | b64enc | quote  }}
  port: {{ printf "5432" | b64enc | quote  }}
  {{- else }}
  dbname: {{ $databaseBackend.name | b64enc | quote }}
  user: {{ $databaseBackend.username | b64enc | quote }}
  password: {{ $databaseBackend.password | b64enc | quote |  }}
  host: {{ $databaseBackend.host | b64enc | quote }}
  port: {{ $databaseBackend.port | b64enc | quote }}
  {{- end }}
{{- end }}