apiVersion: v1
kind: Service
metadata:
  name: {{ include "datakern.fullname" . }}-svc
  labels:
    {{- include "datakern.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http
  selector:
    {{- include "datakern.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "datakern.fullname" . }}-frontend