apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: apache-nas
  name: apache-nas
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apache-nas
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apache-nas
    spec:
      containers:
      - image: {{ .Values.docker_image }}
        name: apache-nas
        resources: {}
        {{- with .Values.env_variables }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: apache-nas-data
            mountPath: /var/www/html
        {{- if .Values.nas.extraVolumeMounts }}
        {{- .Values.nas.extraVolumeMounts | toYaml | nindent 10 }}
        {{- end }}
      volumes:
        - name: apache-nas-data
          persistentVolumeClaim:
            claimName: {{ .Values.nas.volume.pvc_name }}
      {{- if .Values.nas.extraVolumes }}
      {{- .Values.nas.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 6 }}
      {{- end }}
