apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache-nas.fullname" . }}
  labels:
    {{- include "apache-nas.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "apache-nas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "apache-nas.labels" . | nindent 8 }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: apache-nas
        resources: {}
        {{- with .Values.env_variables }}
        env:
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: apache-nas-data
            mountPath: /var/www/html
        {{- if .Values.nas.extraVolumeMounts }}
        {{- .Values.nas.extraVolumeMounts | toYaml | nindent 10 }}
        {{- end }}
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
      volumes:
        - name: apache-nas-data
          persistentVolumeClaim:
            claimName: {{ .Values.nas.volume.pvc_name }}
      {{- if .Values.nas.extraVolumes }}
      {{- .Values.nas.extraVolumes | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 6 }}
      {{- end }}
