apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nas.volume.pvc_name }}
  labels:
    app.camptocamp.com/name: apache-nas
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
    {{- range .Values.nas.volume.accessModes }}
    - {{ . | quote }}
    {{- end }}
  {{- if .Values.nas.volume.storage_class_name  }}
  storageClassName: {{ .Values.nas.volume.storage_class_name }}
  {{- else }}
  storageClassName: ""
  {{- end }}
  {{- if .Values.nas.volume.pv_name  }}
  volumeName: {{ .Values.nas.volume.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nas.volume.storage_size }}
