apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-nas.fullname" . }}-svc
  labels:
    {{- include "apache-nas.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "apache-nas.selectorLabels" . | nindent 4 }}
