apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "apache-nas.fullname" . }}-data
  labels:
    {{- include "apache-nas.labels" . | nindent 4 }}
  {{- with .Values.nas.volume.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.nas.volume.accessModes }}
    - {{ . | quote }}
    {{- end }}
  # disable automatic provisioning
  {{- if (eq "-" .Values.nas.volume.storage_class_name) }}
  storageClassName: ""
  {{- else if .Values.nas.volume.storage_class_name  }}
  storageClassName: {{ .Values.nas.volume.storage_class_name }}
  {{- end }}
  {{- if .Values.nas.volume.pv_name  }}
  volumeName: {{ .Values.nas.volume.pv_name }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.nas.volume.storage_size }}
