{{- $jobConfiguration := .Values.configuration -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acceptance-tests.fullname" . }}-job-secrets
  labels:
    {{- include "acceptance-tests.labels" . | nindent 4 }}
type: Opaque
data:
  georchestraLocalAccountUsername: {{ required ".Values.configuration.georchestra.localAccount.username is required." $jobConfiguration.georchestra.localAccount.username | b64enc | quote }}
  georchestraLocalAccountPassword: {{ required ".Values.configuration.georchestra.localAccount.password is required" $jobConfiguration.georchestra.localAccount.password | b64enc | quote }}
  renaterUsername: {{ required ".Values.configuration.renater.username is required." $jobConfiguration.renater.username | b64enc | quote }}
  renaterPassword: {{ required ".Values.configuration.renater.password is required" $jobConfiguration.renater.password | b64enc | quote }}
