{{- if .Values.secrets.datadirSSHKey }}
apiVersion: v1
data:
  geoserver_datadir_deploy_key: {{ .Values.secrets.datadirSSHKey | b64enc }}
kind: Secret
metadata:
  name: {{ include "geoserver-datadir-sync.fullname" . }}-secret-sync-ssh-key
type: Opaque
{{- end }}
