{{- if .Values.geoserver.jetty_monitoring }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-geoserver-pm
  labels:
    {{- include "georchestra-geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves
spec:
  selector:
    matchLabels:
      {{- include "georchestra-geoserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves
  podMetricsEndpoints:
  - port: prometheus
{{- end }}
