{{- if gt .Values.geoserver.replicas 0.0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves-svc
  labels:
    {{- include "georchestra-geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves
spec:
  ports:
    - name: http-alt
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    {{- include "georchestra-geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves
{{- end -}}
