{{- if gt .Values.geoserver.replicas 0.0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-geoserver-slaves-cm
data:
  sync.py: |-
{{ tpl (.Files.Get "files/sync.py") . | indent 4 }}
{{- end -}}
