apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "apache-mod-mellon.fullname" . }}-apache-depl
  labels:
    {{- include "apache-mod-mellon.labels" . | nindent 4 }}-apache-depl
spec:
  selector:
    matchLabels:
      {{- include "apache-mod-mellon.selectorLabels" . | nindent 6 }}-apache-depl
  template:
    metadata:
      labels:
        {{- include "apache-mod-mellon.selectorLabels" . | nindent 8 }}-apache-depl
    spec:
      containers:
        - name: apache
          image: ghcr.io/camptocamp/inrae-docker-images/apache-mod-mellon:2.4
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
          - name: httpd-config
            mountPath: /usr/local/apache2/conf/httpd.conf
            subPath: httpd.conf
          - name: mod-mellon-config
            mountPath: /etc/mod-mellon-config
      volumes:
      - name: mod-mellon-config
        secret:
          secretName: {{ include "apache-mod-mellon.fullname" . }}-mod-mellon
      - name: httpd-config
        configMap:
          name: {{ include "apache-mod-mellon.fullname" . }}-httpd

