apiVersion: v1
kind: Service
metadata:
  name: {{ include "apache-mod-mellon.fullname" . }}-apache-svc
  labels:
    {{- include "apache-mod-mellon.labels" . | nindent 4 }}-apache-svc
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    {{- include "apache-mod-mellon.selectorLabels" . | nindent 4 }}-apache-depl
