apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
  labels:
    {{- include "apache-mod-mellon.labels" . | nindent 4 }}-apache
  name: {{ include "apache-mod-mellon.fullname" . }}-mod-mellon
data:
  mellon.key: |
    {{ .Values.mellon_config.private_key | b64enc | quote }}

  mellon.cert: |
    {{ .Values.mellon_config.certificate | b64enc | quote }}

  metadata-signing-cert.pem: |
    {{ .Values.mellon_config.metadata_signing_cert | b64enc | quote }}

  metadata-idps.xml: |
    {{ .Values.mellon_config.idps_metadata | b64enc | quote }}