{{- $webapp := .Values.backend -}}
{{- if $webapp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dgechatbot.fullname" . }}-backend-secret
type: Opaque
data:
  DOMAIN: "{{ $webapp.config.domain | b64enc }}"
  FRONTEND_HOST: "{{ $webapp.config.frontendHost | b64enc }}"
  ENVIRONMENT: "{{ $webapp.config.environment | b64enc }}"
  PROJECT_NAME: "{{ $webapp.config.projectName | b64enc }}"
  STACK_NAME: "{{ $webapp.config.stackName | b64enc }}"
  BACKEND_CORS_ORIGINS: "{{ $webapp.config.backendCorsOrigins | b64enc }}"
  SECRET_KEY: "{{ $webapp.config.secretKey | b64enc }}"

  # LLM
  LLM_MODEL: "{{ $webapp.config.llm.model | b64enc }}"
  LLM_API_KEY: "{{ $webapp.config.llm.apiKey | b64enc }}"
  PHOENIX_COLLECTOR_ENDPOINT: "{{ printf "http://%s-phoenix-svc:6006" .Release.Name | b64enc }}"

  # MistralAI
  MISTRALAI_API_KEY: "{{ $webapp.config.mistralAI.apiKey | b64enc }}"

  # Geonetwork Elasticsearch
  GN_ES_URL: "{{ $webapp.config.elasticSearch.url | b64enc }}"

  # Testset generation
  TEST_GENERATION_MODEL: "{{ $webapp.config.testGenerationModel.name | b64enc }}"
  TEST_GENERATION_MODEL_KEY: "{{ $webapp.config.testGenerationModel.key | b64enc }}"

  METADATA_URL: "{{ $webapp.config.metadataUrl | b64enc }}"
{{- end }}
