{{- $webapp := .Values.backend -}}
{{- if $webapp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dgechatbot.fullname" . }}-backend-config
data:
  DOMAIN: "{{ $webapp.config.domain }}"
  FRONTEND_HOST: "{{ $webapp.config.frontendHost }}"
  ENVIRONMENT: "{{ $webapp.config.environment }}"
  PROJECT_NAME: "{{ $webapp.config.projectName }}"
  STACK_NAME: "{{ $webapp.config.stackName }}"
  BACKEND_CORS_ORIGINS: "{{ $webapp.config.backendCorsOrigins }}"
  SECRET_KEY: "{{ $webapp.config.secretKey }}"

  # LLM
  LLM_MODEL: "{{ $webapp.config.llm.model }}"
  LLM_API_KEY: "{{ $webapp.config.llm.apiKey }}"
  PHOENIX_COLLECTOR_ENDPOINT: "http://{{ .Release.Name }}-phoenix-svc:6006"

  # MistralAI
  MISTRALAI_API_KEY: "{{ $webapp.config.mistralAI.apiKey }}"

  # Geonetwork Elasticsearch
  GN_ES_URL: "{{ $webapp.config.elasticSearch.url }}"

  # Testset generation
  TEST_GENERATION_MODEL: "{{ $webapp.config.testGenerationModel.name }}"
  TEST_GENERATION_MODEL_KEY: "{{ $webapp.config.testGenerationModel.key }}"
{{- end }}
