---
geoserver:
  # This is the url to the service provided by the geOrchestra helm chart
  master_svc_url: georchestra-geoserver-svc:8080
  docker_image: georchestra/geoserver:24.0.10
  docker_image_pull_policy: IfNotPresent
  resources:
    requests:
      memory: "2048Mi"
      cpu: "100m"
    limits:
      memory: "8192Mi"
  tolerations: []
  livenessProbe:
    httpGet:
      path: /geoserver/ows?SERVICE=WMS&LAYERS=geor:public_layer&FORMAT=image/png&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-20820223,-20820223,20820223,20820223&WIDTH=10&HEIGHT=10
      port: 8080
      scheme: HTTP
      httpHeaders:
      - name: ctrl-flow-priority
        value: "true"
    periodSeconds: 10
    failureThreshold: 3
    successThreshold: 1
    timeoutSeconds: 5
  # pull_secret: ghcr-registry-secret
  replicas: 1
  jetty_monitoring: false
  git:
    repository_url: git@github.com:org/georchestra-client-configuration.git
    branch: k8s-master
  reloader:
    docker_image: python:3.9
    http_headers: "{ 'sec-username': 'superadmin', 'sec-roles': 'ROLE_ADMINISTRATOR', 'Accept': 'application/xml' }"
  extra_environment: []
  extra_volumes: []
  volumes:
    geoserverDatadir:
      persistentVolumeClaim:
        claimName: georchestra-geoserver-datadir

nginx:
  resources:
    requests:
      memory: "64Mi"
    limits:
      memory: "128Mi"
  image:
    repository: docker.io
    name: nginx
    tag: '1.23.3'
    pullPolicy: IfNotPresent
  absolute_redirect: 'off'

database:
  auth:
    existingSecret: mysecret
  geodata:
    auth:
      existingSecret: mysecret
  datafeeder:
    auth:
      existingSecret: mysecret
  gwc:
    auth:
      existingSecret: mysecret
