---
geoserver:
  # This is the url to the service provided by the geOrchestra helm chart
  master_svc_url: georchestra-geoserver-svc:8080
  docker_image: georchestra/geoserver:24.0.10
  docker_image_pull_policy: IfNotPresent
  resources:
    requests:
      memory: "2048Mi"
      cpu: "100m"
    limits:
      memory: "8192Mi"
  tolerations: []
  # pull_secret: ghcr-registry-secret
  replicas: 1
  git:
    docker_image: alpine/git:2.49.1
    docker_image_pull_policy: IfNotPresent
    repository_url: git@github.com:org/georchestra-client-configuration.git
    branch: k8s-master
  reloader:
    docker_image: ghcr.io/camptocamp/georchestra-docker-images/geoserver-lb-geoserver-sync:20250827
    docker_image_pull_policy: IfNotPresent
  extra_environment: []
  extra_volumes: []
  extra_volumeMounts: []
  extraContainers: []
  volumes:
    geoserverDatadir:
      persistentVolumeClaim:
        claimName: georchestra-geoserver-datadir

nginx:
  resources:
    requests:
      memory: "64Mi"
    limits:
      memory: "128Mi"
  image:
    repository: docker.io
    name: nginx
    tag: '1.23.3'
    pullPolicy: IfNotPresent
  absolute_redirect: 'off'

database:
  auth:
    existingSecret: mysecret
  geodata:
    auth:
      existingSecret: mysecret
  datafeeder:
    auth:
      existingSecret: mysecret
  gwc:
    auth:
      existingSecret: mysecret
