{{- if gt .Values.geoserver.replicas 0.0 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-lb
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    {{- include "georchestra-geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}-geoserver-lb
  sessionAffinity: None
  type: ClusterIP
{{- end }}
