{{- if gt .Values.geoserver.replicas 0.0 -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-geoserver-lb-cm
data:
  default.conf: |
    upstream gs-ui {
      server {{ .Values.geoserver.master_svc_url }};
    }
    upstream gs-backend {
      server {{ include "georchestra-geoserver.fullname" . }}-slaves:8080;
    }
    server {
        listen       8080;
        server_name  localhost;

        absolute_redirect {{ .Values.nginx.absolute_redirect }};

        location /geoserver/web {
          proxy_pass http://gs-ui;
        }
        location /geoserver/rest {
          proxy_pass http://gs-ui;
        }
        location /geoserver/gwc/rest {
          proxy_pass http://gs-ui;
        }
        location ~* /geoserver/(.*)/(.*)/wms {
          proxy_pass http://gs-backend/geoserver/wms?$args;
        }
        location /geoserver {
          if ($args  ~* service=wps) {
            proxy_pass http://gs-ui;
          }
          proxy_pass http://gs-backend;
        }
    }
  nginx.conf: |
    user  nginx;
    worker_processes 4;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;


    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                          '$status $body_bytes_sent "$http_referer" '
                          '"$http_user_agent" "$http_x_forwarded_for" ' '$request_time';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        #gzip  on;

        include /etc/nginx/conf.d/*.conf;
    }
{{- end }}
