apiVersion: v1
data:
  geoserver_datadir_deploy_key: {{ .Values.gs_datadir_sync.git_private_key | b64enc }}
kind: Secret
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-gs-datadir-sync-secret
type: Opaque
