---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra-geoserver.fullname" . }}-gs-datadir-sync
  labels:
    {{- include "georchestra-geoserver.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}--gs-datadir-sync
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra-geoserver.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}--gs-datadir-sync
  template:
    metadata:
      labels:
        {{- include "georchestra-geoserver.selectorLabels" . | nindent 8 }}
        org.georchestra.geoserver.service/name: {{ include "georchestra-geoserver.fullname" . }}--gs-datadir-sync
        app.kubernetes.io/component: {{ include "georchestra-geoserver.fullname" . }}--gs-datadir-sync
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: gs-datadir-sync
        image: {{ .Values.gs_datadir_sync.docker_image }}
        imagePullPolicy: Always
        env:
        - name: GIT_RSA_DEPLOY_KEY_FILE
          value: /tmp/secrets/geoserver_datadir_deploy_key
        {{- with .Values.gs_datadir_sync.extra_environment }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
          - name: geoserver-datadir
            mountPath: /var/local/data
          - name: gs-datadir-sync-secret
            mountPath: /tmp/secrets
      volumes:
      - name: gs-datadir-sync-secret
        secret:
          secretName: {{ include "georchestra-geoserver.fullname" . }}-gs-datadir-sync-secret
      - name: geoserver-datadir
      {{- with .Values.gs_datadir_sync.gs_datadir_volume_spec -}}
      {{ . | toYaml | nindent 8 }}
      {{- end -}}
      {{- with .Values.gs_datadir_sync.docker_pull_secret }}
      imagePullSecrets:
      - name: {{ . }}
      {{- end }}
