# Default values for vrt-bot.
replicaCount: 1
image:
  repository: georchestra/vrt-bot
  pullPolicy: IfNotPresent
  tag: "build-d48d2d469687ef0c1a5a5237d0a68334f69934bf"

imagePullSecrets: []
podAnnotations: {}
extra_env:
  - name: ACTIVESCHEMA
    value: public
  - name: PGCLIENTENCODING
    value: utf8
  - name: PGDATABASE
    valueFrom:
      secretKeyRef:
        name: dev-vrt-bot.dev-vrt-bot
        key: dbname
  - name: PGHOST
    valueFrom:
      secretKeyRef:
        name: dev-vrt-bot.dev-vrt-bot
        key: host
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        name: dev-vrt-bot.dev-vrt-bot
        key: password
  - name: PGPORT
    valueFrom:
      secretKeyRef:
        name: dev-vrt-bot.dev-vrt-bot
        key: port
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        name: dev-vrt-bot.dev-vrt-bot
        key: user
  - name: SOURCEDIR
    value: /home/app/apache-nas/vrts

volumes:
  - name: apache-nas-data
    persistentVolumeClaim:
      claimName: apache-nas-data-dev

volumeMounts:
  - name: apache-nas-data
    mountPath: /home/app/apache-nas

schedule: "*/15 * * * *"

tolerations: []
affinity: {}
resources: {}