{{- if .Values.ogcFeatConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels: opendata-ogc-features
  name: ogc-feat-config-cm
data:
  application.yaml: |
    {{- .Values.ogcFeatConfig | nindent 4 }}
{{- end }}