{{- if .Values.ogcFeatConfig }}
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
  labels:
  - app.kubernetes.io/component: opendata-ogc-features
  name: ogc-feat-config-cm
data:
  application.yaml: |
    {{- .Values.ogcFeatConfig |  nindent 4 }}
{{- end }}