---
cronjobs:
  - name: grafana-report
    schedule: TBD
    image: camptocamp/grafana-reporter:latest
    imagePullPolicy: IfNotPresent
    args: []
    envs: []
    volumes: []
    tolerations: []
    affinity: {}
    resources: {}
