apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "geocontrib.fullname" . }}-celery-depl
  labels:
    {{- include "geocontrib.labels" . | nindent 4 }}-celery-depl
    app.neogeo.fr: geocontrib
spec:
  selector:
    matchLabels:
      {{- include "geocontrib.selectorLabels" . | nindent 6 }}-celery-depl
  template:
    metadata:
      labels:
        {{- include "geocontrib.selectorLabels" . | nindent 8 }}-celery-depl
    spec:
      containers:
        - name: celery
          image: {{ .Values.celery.image }}
          imagePullPolicy: {{ .Values.celery.pullPolicy }}
          command:
          - src/docker/geocontrib/docker-entrypoint.sh
          args:
          - src/docker/geocontrib/start_celery.sh
          {{- with .Values.env_variables }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
            - name: REDIS_HOST
              value: {{ include "geocontrib.fullname" . }}-redis-svc
          resources:
            {{- toYaml .Values.celery.resources | nindent 12 }}
          volumeMounts:
          - name: geocontrib-config
            mountPath: /home/apprunner/geocontrib_app/config_front
          - name: geocontrib-media
            mountPath: /home/apprunner/geocontrib_app/media
          - name: geocontrib-static
            mountPath: /home/apprunner/geocontrib_app/static
      volumes:
      - name: geocontrib-config
        configMap:
          name: {{ include "geocontrib.fullname" . }}-config-front-cm
      - name: geocontrib-media
        persistentVolumeClaim:
          claimName: {{ include "geocontrib.fullname" . }}-geocontrib-media-pvc
      - name: geocontrib-static
        persistentVolumeClaim:
          claimName: {{ include "geocontrib.fullname" . }}-geocontrib-static-pvc
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
