{{- if .Values.config.adminUser }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pgbouncer.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ template "pgbouncer.name" . }}
    helm.sh/chart: {{ template "pgbouncer.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  adminUser: {{ .Values.config.adminUser | b64enc | quote }}
  adminPassword: {{ .Values.config.adminPassword | b64enc | quote }}
{{- end }}