---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rclone.name" . }}
  labels:
    {{- include "rclone.labels" . | nindent 4 }}
data:
  rclone.conf: |
{{ .Values.rclone.config  | indent 4 }}
