---
{{ if .Values.enableExternalSecrets }}
{{- range $_, $v := .Values.remoteBackendsExternalSecrets }}
apiVersion: "external-secrets.io/v1alpha1"
kind: ExternalSecret
metadata:
  name: {{ include "rclone.name" $ }}-remote-{{ $v }}-external-secret
  labels:
    {{- include "rclone.labels" $ | nindent 4 }}
spec:
  secretStoreRef:
    name: cluster-secretstore
    kind: ClusterSecretStore
  target:
    name: {{ $v }}-provider-s3-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        {{ $v | replace " " "_" | replace "-" "_" }}_provider.creds: "{{ `{{ .creds_file }}` }}"
  data:
  - secretKey: creds_file
    remoteRef:
      key: {{ $v }}
{{- end }}
{{ end }}
---
