---
{{ if .Values.enablePlainSecrets }}
{{- range $_, $v := .Values.remoteBackendsSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rclone.name" $ }}-remote-{{ $v.name }}-secret
  labels:
    {{- include "rclone.labels" $ | nindent 4 }}
type: Opaque
data:
  {{ $v.name | replace " " "_" | replace "-" "_" }}_provider.creds: {{ $v.data }}
{{- end }}
{{ end }}
---
