apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "vrt-bot.fullname" . }}
  labels:
    {{- include "vrt-bot.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 3
  jobTemplate:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "vrt-bot.selectorLabels" . | nindent 8 }}
    spec:
      template:
        ttlSecondsAfterFinished: 3600
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumes:
          {{- .Values.volumes | toYaml | nindent 10 }}
          initContainers:
            - name: create-sourcedir
              image: "{{ .Values.image }}"
              command: ['sh', '-c', "mkdir -p $SOURCEDIR; chown app:app $SOURCEDIR"]
              securityContext:
                runAsUser: 0
              volumeMounts:
              {{- .Values.volumeMounts | toYaml | nindent 14 }}
              env:
              {{- .Values.extra_env | toYaml | nindent 14 }}
          containers:
            - name: vrt-bot
              image: "{{ .Values.image }}"
              imagePullPolicy: {{ .Values.pullPolicy }}
              volumeMounts:
              {{- .Values.volumeMounts | toYaml | nindent 14 }}
              env:
              {{- .Values.extra_env | toYaml | nindent 14 }}
          restartPolicy: Never
