apiVersion: v2
name: mviewer
description: A Helm chart to deploy the mviewer stack
type: application
version: 0.2.9
appVersion: "3.9"
maintainers:
  - name: geOrchestra
    url: https://www.georchestra.org
