{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm-mviewer.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}

kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-mviewer.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts | default (list "") }}
    {{- if $.Values.ingress.hosts }}
    - host: {{ .host | quote }}
    {{- else }}
    - host: {{ $.Values.fqdn | quote }}
    {{- end }}
      http:
        paths:
          {{- if $.Values.mviewer.enabled }}
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "helm-mviewer.fullname" $ }}-mviewer-svc
                port:
                  number: 80
              {{- else }}
              serviceName: {{ include "helm-mviewer.fullname" $ }}-mviewer-svc
              servicePort: 80
              {{- end }}
          {{- end }}
          {{- if $.Values.mviewerstudio.enabled }}
          - path: /mviewerstudio
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "helm-mviewer.fullname" $ }}-mviewerstudio-svc
                port:
                  number: 8000
              {{- else }}
              serviceName: {{ include "helm-mviewer.fullname" $ }}-mviewerstudio-svc
              servicePort: 8000
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
