{{- if .Values.mviewer.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-mviewer.fullname" . }}-mviewer-deployment
  labels:
    {{- include "helm-mviewer.labels" . | nindent 4 }}-mviewer
    application/name: {{ include "helm-mviewer.fullname" . }}-mviewer-deployment
spec:
  replicas: {{ .Values.mviewer.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-mviewer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.mviewer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-mviewer.selectorLabels" . | nindent 8 }}-mviewer
        application/name: {{ include "helm-mviewer.fullname" . }}-mviewer-deployment
    spec:
      {{- if .Values.mviewer.configuration.git.url }}
      initContainers:
      {{- include "mviewer.bootstrap_mviewer_configuration" $ | nindent 6 }}
      {{- end }}
      {{- with .Values.mviewer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.mviewer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.mviewer.securityContext | nindent 12 }}
          image: "{{ .Values.mviewer.image.repository }}:{{ .Values.mviewer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.mviewer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          {{- with .Values.mviewer.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.mviewer.resources | nindent 12 }}
          {{- with .Values.mviewer.extra_environment }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.mviewer.configuration.git.url }}
          volumeMounts:
            - name: mviewer-configuration
              mountPath: /usr/share/nginx/html/apps
          {{- else if .Values.mviewer.extraVolumeMounts }}
          volumeMounts:
          {{- .Values.mviewer.extraVolumeMounts | toYaml | nindent 10 }}
          {{- end }}
      {{- if .Values.mviewer.configuration.git.url }}
      volumes:
        - name: mviewer-configuration
          emptyDir: {}
        - name: ssh-secret
          secret:
            secretName: {{ .Values.mviewer.configuration.git.ssh_secret }}
            defaultMode: 0400
      {{- else if .Values.mviewer.extraVolumes }}
      volumes:
      {{- .Values.mviewer.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      {{- with .Values.mviewer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mviewer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mviewer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
