{{- if .Values.mviewer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-mviewer.fullname" . }}-mviewer-svc
  labels:
    {{- include "helm-mviewer.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mviewer.service.type }}
  ports:
    - port: {{ .Values.mviewer.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    application/name: {{ include "helm-mviewer.fullname" . }}-mviewer-deployment
{{- end }}
