apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-svc
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.kubernetes.io/name: sftp
spec:
  type: {{ .Values.sftp.service.type }}
  {{- if .Values.sftp.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.sftp.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.sftp.service.port }}
      protocol: TCP
      targetPort: 22
      {{- if .Values.sftp.service.nodePort }}
      nodePort: {{ .Values.sftp.service.nodePort }}
      {{- end }}
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}
