apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-svc
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.georchestra.org: sftp
spec:
  type: ClusterIP
  ports:
    - port: 22
      protocol: TCP
      targetPort: 22
  selector:
    {{- include "sftp.selectorLabels" . | nindent 4 }}
