apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-depl
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "sftp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sftp.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/sftp-cm.yaml") . | sha256sum }}
    spec:
      {{- with .Values.sftp.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sftp
          image: {{ .Values.sftp.image }}
          imagePullPolicy: {{ .Values.sftp.imagePullPolicy }}
          resources:
            {{- toYaml .Values.geoserver.resources | nindent 12 }}
          {{- with .Values.sftp.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: authorized-keys
              mountPath: /tmp/dotssh
            - name: hostkeys
              mountPath: /tmp/hostkeys
            - name: etc-hostkeys
              mountPath: /etc/ssh/ssh_host_keys
          {{- if .Values.sftp.extraVolumeMounts }}
          {{- .Values.sftp.extraVolumeMounts | toYaml | nindent 12 }}
          {{- end }}
          command:
            - /bin/bash
            - -c
            - cp /tmp/hostkeys/* /etc/ssh/ssh_host_keys/ ; chmod 600 /etc/ssh/ssh_host_keys/* ;
              mkdir -p /home/sftp/.ssh ;
              chmod 700 /home/sftp/.ssh ;
              chown sftp:sftp /home/sftp ;
              chown sftp:sftp /home/sftp/.ssh ;
              cp -f /tmp/dotssh/authorized_keys /home/sftp/.ssh/authorized_keys ;
              chmod 600 /home/sftp/.ssh/authorized_keys ;
              chown sftp:sftp /home/sftp/.ssh/authorized_keys ;
              /usr/sbin/sshd -D -e ;
      hostname: {{ tpl .Values.sftp.customHostname . }}
      volumes:
      - name: authorized-keys
        configMap:
          name: {{ include "sftp.fullname" . }}-sftp-cm
      - name: hostkeys
        configMap:
          name: {{ include "sftp.fullname" . }}-sftp-hostkeys-cm
      - name: etc-hostkeys
        emptyDir: {}
      {{- if .Values.sftp.extraVolumes }}
      {{- .Values.sftp.extraVolumes | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.sftp.tolerations }}
      tolerations:
        {{- .Values.sftp.tolerations | toYaml | nindent 6 }}
      {{- end }}
status: {}
