apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-hostkeys-cm
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
    app.kubernetes.io/name: sftp
data:
  {{- range $filename, $contents := .Values.sftp.host_keys }}
  {{ $filename }}: |
    {{- $contents | trim | nindent 4 }}
  {{- end }}
