apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sftp.fullname" . }}-sftp-cm
  labels:
    {{- include "sftp.labels" . | nindent 4 }}
data:
  authorized_keys: |
    {{- .Values.sftp.authorized_keys | nindent 4 }}
