image:
  repository: ghcr.io/camptocamp/inrae-docker-images/apache-mod-mellon
  pullPolicy: IfNotPresent
  tag: "2.4-build-20250224"
hostname: https://inrae.sandbox.apps.gs-fr-prod.camptocamp.com:443
# Enable for ProxyPass mode
#georchestra_proxypass_endpoint: http://georchestra-gateway-svc:8080/
# Can be RequestHeader when in ProxyPass mode
apache_auth_headers_type: "Header"
mellon_config:
  entity_id: https://poc-renater.inrae.sandbox.apps.gs-fr-prod.camptocamp.com/
  certificate: |
    -----BEGIN CERTIFICATE-----
      ....
    -----END CERTIFICATE-----

  private_key: |
    -----BEGIN PRIVATE KEY-----
      ....
    -----END PRIVATE KEY-----
  metadata_signing_cert: |
    -----BEGIN CERTIFICATE-----
      ....
    -----END CERTIFICATE-----
  idps_metadata: |
    <?xml version='1.0' encoding='UTF-8'?>
      ....
    </md:EntitiesDescriptor>

  # * https://discovery.renater.fr/test/WAYF?cru=yes for test
  # * https://discovery.renater.fr/renater/WAYF?cru=yes for prod
  discovery_url: https://discovery.renater.fr/test/WAYF?cru=yes
  organization_url: https://www.inrae.fr
  organization_name: INRAE
  provider_id: renater
  set_env:
    mail: urn:oid:0.9.2342.19200300.100.1.3
    eppn: urn:oid:1.3.6.1.4.1.5923.1.1.1.6
    cn: urn:oid:2.5.4.3
    o: urn:oid:2.5.4.10
    sn: urn:oid:2.5.4.4
    given_name: urn:oid:2.5.4.42
