apiVersion: v1
kind: Service
metadata:
  name: {{ include "wireproxy.fullname" . }}
  labels:
    {{- include "wireproxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: wireguard
      protocol: UDP
      name: wireguard
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "wireproxy.selectorLabels" . | nindent 4 }}
