name: Helm publish on new commit

on:
  push:
    branches:
      - '*'
      - '!gh-pages'

jobs:
  chart-publish-on-commit:
    runs-on: ubuntu-latest
    steps:
      - name: main Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: charts-gs
      - name: gh-pages Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: 'gh-pages'
          path: gh-pages
      - name: Helm Installation
        uses: azure/setup-helm@v3
        with:
          version: v3.10.2
      - name: Helm Package all the charts using commit ID and remove chart packages older than 6 months
        shell: bash
        run: |
          cd charts-gs
          for directory in *; do
            if [ -d "$directory" ]; then
                helm package "$directory" -d ../gh-pages --version $(helm show chart "$directory" |grep version: | awk '{print $2}')-"$GITHUB_REF_NAME"-"${GITHUB_SHA::7}"
            fi
          done
          cd ../gh-pages
          find . -type f -mtime +180 -delete
          helm repo index . --merge index.yaml
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
