{{- $job := .Values.job -}}
{{- $ldapTargetConfiguration := .Values.configuration.ldapTarget -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "georchestra-backup-ldap.fullname" . }}
  labels:
    {{- include "georchestra-backup-ldap.labels" . | nindent 4 }}
spec:
  schedule: {{ $job.schedule | quote }}
  successfulJobsHistoryLimit: {{ $job.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 86400
      template:
        metadata:
          labels:
            {{- include "georchestra-backup-ldap.labels" . | nindent 12 }}
        spec:
          {{- with $job.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- with $job.podSecurityContext }}
          securityContext:
            {{ toYaml . | nindent 10 }}
          {{- end }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ $job.image.repository }}:{{ $job.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ $job.image.pullPolicy }}
            volumeMounts:
              - mountPath: /backup
                name: backup
            command: ["/bin/bash", "-c"]
            args:
            - |
              TSTP=$(date +"%s") ;
              /usr/bin/ldapsearch -H {{ $ldapTargetConfiguration.service }} -xLLL -D "{{ $ldapTargetConfiguration.adminDn }}" -w {{ $ldapTargetConfiguration.secret }} -b "{{ $ldapTargetConfiguration.usersRdn }},{{ $ldapTargetConfiguration.baseDn }}" > /backup/ldap-${TSTP}.ldif;
              /usr/bin/ldapsearch -H {{ $ldapTargetConfiguration.service }} -xLLL -D "{{ $ldapTargetConfiguration.adminDn }}" -w {{ $ldapTargetConfiguration.secret }} -b "{{ $ldapTargetConfiguration.pendingusersRdn }},{{ $ldapTargetConfiguration.baseDn }}" >> /backup/ldap-${TSTP}.ldif;
              /usr/bin/ldapsearch -H {{ $ldapTargetConfiguration.service }} -xLLL -D "{{ $ldapTargetConfiguration.adminDn }}" -w {{ $ldapTargetConfiguration.secret }} -b "{{ $ldapTargetConfiguration.orgsRdn }},{{ $ldapTargetConfiguration.baseDn }}" >> /backup/ldap-${TSTP}.ldif;
              /usr/bin/ldapsearch -H {{ $ldapTargetConfiguration.service }} -xLLL -D "{{ $ldapTargetConfiguration.adminDn }}" -w {{ $ldapTargetConfiguration.secret }} -b "{{ $ldapTargetConfiguration.pendingorgsRdn }},{{ $ldapTargetConfiguration.baseDn }}" >> /backup/ldap-${TSTP}.ldif;
              /usr/bin/ldapsearch -H {{ $ldapTargetConfiguration.service }} -xLLL -D "{{ $ldapTargetConfiguration.adminDn }}" -w {{ $ldapTargetConfiguration.secret }} -b "{{ $ldapTargetConfiguration.rolesRdn }},{{ $ldapTargetConfiguration.baseDn }}" >> /backup/ldap-${TSTP}.ldif;
              find /backup -name '*.ldif' -mtime +{{.Values.configuration.backupRetentionDays}} -delete ;
            {{- with $job.resources }}
            resources:
              {{ toYaml . | nindent 12 }}
            {{- end }}
            {{- with $job.securityContext }}
            securityContext:
              {{ toYaml . | nindent 12 }}
            {{- end }}
          restartPolicy: {{ $job.restartPolicy }}
          volumes:
            - name: "backup"
              persistentVolumeClaim:
                claimName: {{ include "georchestra-backup-ldap.fullname" . }}-pvc
          {{- with $job.nodeSelector }}
          nodeSelector:
            {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with $job.affinity }}
          affinity:
            {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- with $job.tolerations }}
          tolerations:
            {{ toYaml . | nindent 10 }}
          {{- end }}
