kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "georchestra-backup-ldap.fullname" . }}-pvc
  labels:
    {{- include "georchestra-backup-ldap.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    {{- range .Values.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  storageClassName: ""
  selector:
    matchLabels:
      {{- include "georchestra-backup-ldap.selectorLabels" . | nindent 6 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.existingPV }}
  volumeName: {{ .Values.persistence.existingPV }}
  {{- end }}
  {{- if .Values.persistence.storageClass }}
  {{- if eq "-" .Values.persistence.storageClass }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}